name: Linting

on: pull_request

jobs:
  pytest:
    name: ruff
    runs-on: ubuntu-latest

    steps:
      - name: "Download code"    
        uses: actions/checkout@v4

      - name: "Install Python 3.13"
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'    

      - name: "Install Poetry"
        run: pipx install poetry

      - name: "Install dependencies"
        run: poetry install

      - name: "Run linting"
        run: poetry run task lint